function START()
%% addpath
% recon model
addpath model/
% GUI callback
addpath callback/

%% figure
% figure handle
f = figure('Menubar','none',...
    'Toolbar','none',...
    'pos',[100 100 1100 500],...
    'resize','off',...
    'NumberTitle','off',...
    'Name','SPECT-recon    by Xu Junshen');

%% FBP Panel
FBP_panel = uipanel('Parent',f,...
    'Title','FBP',...
    'FontSize',12,...
    'FontAngle','italic',...
    'Position',[0.75,0.75,0.22,0.20],...
    'FontName','Times New Roman');

% checkbox: use filter or not (FBP or BP)
IsFiltered = uicontrol('Style','checkbox',...
    'Parent',FBP_panel,...
    'String','use ramp filter',...
    'FontSize',11,...
    'Position',[20,55,200,20],...
    'FontName','Times New Roman',...
    'Value',1);

uicontrol('Style','text',...
    'Parent',FBP_panel,...
    'String','cut-off frequency (0 to 1)',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,15,150,25]);

% set cut-off frequency for FBP
hfreq = uicontrol('Style','edit',...
    'Parent',FBP_panel,...
    'Position',[175,20,40,20],...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'String','1');

%% OSEM Panel

OSEM_panel = uibuttongroup('Parent',f,...
     'Title','OSEM',...
     'FontSize',12,...
     'FontAngle','italic',...
     'Position',[0.75,0.51,0.22,0.22],...
     'FontName','Times New Roman');

uicontrol('Style','text',...
    'Parent',OSEM_panel,...
    'String','number of iterations',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,60,120,25]);

% set number of iterations for OSEM
hIter = uicontrol('Style','edit',...
    'Parent',OSEM_panel,...
    'Position',[175,65,40,20],...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'String','2');

uicontrol('Style','text',...
    'Parent',OSEM_panel,...
    'String','number of subsets',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,35,110,25]);

% use 1 subset, i.e. MLEM
hMLEM = uicontrol('Style','Radio',...
     'String','1 subset',...
     'pos',[20 15 100 20],...
     'FontSize',11,...
     'Parent',OSEM_panel,...
     'FontName','Times New Roman',...
     'Value', 1);

% use 4 subsets, OSEM
uicontrol('Style','Radio',...
     'String','4 subsets',...
     'FontSize',11,...
     'FontName','Times New Roman',...
     'pos',[130 15 100 20],...
     'Parent',OSEM_panel);

%% Post Filter Panel
% set parameters for post gaussian fitler
PostFilter_panel = uipanel('Parent',f,...
    'Title','Post-Filter',...
    'FontSize',12,...
    'FontAngle','italic',...
    'Position',[0.75,0.30,0.22,0.20],...
    'FontName','Times New Roman');

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','sigma x',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,55,100,25]);

% sigma in x-direction
hsx = uicontrol('Style','edit',...
    'Parent',PostFilter_panel,...
    'Position',[120,60,40,20],...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'String','2.03'); 

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','mm',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[160,55,50,25]);

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','sigma y',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,30,100,25]);

% set sigma in y-direction
hsy = uicontrol('Style','edit',...
    'Parent',PostFilter_panel,...
    'Position',[120,35,40,20],...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'String','2.03'); 

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','mm',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[160,30,50,25]);

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','sigma z',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[20,5,100,25]);

% set sigma in z-direction
hsz = uicontrol('Style','edit',...
    'Parent',PostFilter_panel,...
    'Position',[120,10,40,20],...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'String','1.56'); 

uicontrol('Style','text',...
    'Parent',PostFilter_panel,...
    'String','mm',...
    'FontSize',11,...
    'FontName','Times New Roman',...
    'Position',[160,5,50,25]);

%% display result
% read projection data
fid = fopen('../../data/whole_bone.raw');
projData = fread(fid, inf, 'float32');
fclose(fid);

% init image
global im
im = ones(128, 128, 128);

% orientation 1
ha1 = axes(f,'Position',[0.01,0.50,0.23,0.4]);
hf1 = imshow(im(:,:,64), []);
hs1 = uicontrol('Parent', f, ...
    'Style', 'slider',...
    'SliderStep',[1/128 1/128],...
    'Min',1, 'Max',128, 'Value',64,...
    'Units', 'Normalized',...
    'Position', [0.01,0.30,0.23,0.05],...
    'Callback', {@slider_callback,hf1,ha1,1});

% orientation 2
ha2 = axes(f,'Position',[0.25,0.50,0.23,0.4]);
hf2 = imshow(squeeze(im(:,64,:)), []);
hs2 = uicontrol('Parent', f, ...
    'Style', 'slider',...
    'SliderStep',[1/128 1/128],...
    'Min',1, 'Max',128, 'Value',64,...
    'Units', 'Normalized',...
    'Position', [0.25,0.30,0.23, 0.05],...
    'Callback', {@slider_callback,hf2,ha2,2});

% orientation 3
ha3 = axes(f,'Position',[0.49,0.50,0.23,0.4]);
hf3 = imshow(squeeze(im(64,:,:)), []);
hs3 = uicontrol('Parent', f, ...
    'Style', 'slider',...
    'SliderStep',[1/128 1/128],...
    'Min',1, 'Max',128, 'Value',64,...
    'Units', 'Normalized',...
    'Position', [0.49,0.30,0.23,0.05],...
    'Callback', {@slider_callback,hf3,ha3,3});

%% method selection
% select FBP or OSEM
h = uibuttongroup('Parent',f,...
     'Title','Method',...
     'FontSize',12,...
     'FontAngle','italic',...
     'Position',[0.75,0.08,0.22,0.18],...
     'FontName','Times New Roman');

% radio button for FBP
hFBP = uicontrol('Style','Radio',...
     'String','FBP',...
     'pos',[20 45 100 30],...
     'FontSize',11,...
     'Parent',h,...
     'FontName','Times New Roman',...
     'Value', 0);

% radio button for OSEM
uicontrol('Style','Radio',...
     'String','OSEM',...
     'FontSize',11,...
     'FontName','Times New Roman',...
     'pos',[130 45 100 30],...
     'Parent',h,...
     'Value', 1);

% button for starting reconstruction
uicontrol('String','Reconstruction',...
    'FontSize',11,...
    'Parent',h,...
    'Position',[70,10,100,25],...
    'FontName','Times New Roman',...
    'Callback',{@recon_callback, hs1, hs2, hs3, IsFiltered, ...
    hfreq, hIter, hMLEM, ...
    hsx, hsy, hsz, hFBP, projData, ...
    hf1, hf2, hf3, ha1, ha2, ha3});
end
